title: 纯纯写作
description: 纯纯写作是一个令人感到安心、启动飞快、有许多纯文本写作辅助和良好体验的产品
email: drakeet.me@gmail.com
theme: jekyll-theme-minimal
logo: images/s720.png
logo_full: images/s.png
show_downloads: true
google_play: https://play.google.com/store/apps/details?id=com.drakeet.purewriter
coolapk: https://a.app.qq.com/o/simple.jsp?pkgname=com.drakeet.purewriter
direct: https://github.com/PureWriter/resources/releases/download/v6.3.6/PureWriter-6.3.6.apk
